server:
  port: 8888
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static,classpath:/templates
  redis:
    database: 0
    host: 192.168.2.144
    port: 6379
    password: ''
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1200